workflows:
  ios-debug:
    name: iOS Debug Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branches:
        - bhuvi
    scripts:
      - name: Set up dependencies
        script: |
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios && pod install
      - name: Build iOS app
        script: |
          flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
